/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;



import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.Airports;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.AirportsRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class AirportsServiceImpl implements AirportsService {

	@Autowired
	private AirportsRepository airportsRepository;

	@Override
	public Airports getOne(Integer airportCode) {
		return airportsRepository.findById(airportCode).get();
	}

	@Override
	public Boolean delete(Integer airportCode) {
		if (airportsRepository.getOne(airportCode) != null) {
			airportsRepository.deleteById(airportCode);
			return true;
		}
		return false;
	}

	@Override
	public Airports create(Airports airports) {
		return airportsRepository.save(airports);
	}

	@Override
	public Airports update(Airports airportsToUpdate) {
						Airports airports = airportsRepository.getOne(airportsToUpdate.getAirportCode());
																		
				if(airportsToUpdate.getAirportName() !=null) {
			
		}
				if(airportsToUpdate.getAirportLocation() !=null) {
			
		}
				if(airportsToUpdate.getOtherDetails() !=null) {
			
		}
				return airportsRepository.save(airports);
	}

	@Override
	public Boolean exist(Airports airports) {
						return airportsRepository.existsById(airports.getAirportCode());
																	}

	@Override
	public List<Airports> findAll() {
		return airportsRepository.findAll();
	}

	@Override
	public Page<Airports> findAll(Pageable pageable) {
		return airportsRepository.findAll(pageable);
	}
}





