/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.BookingAgents;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface BookingAgentsService {

	BookingAgents getOne(Integer agentId);

	List<BookingAgents> findAll();

	Page<BookingAgents> findAll(Pageable pageable);

	Boolean delete(Integer agentId);

	BookingAgents create(BookingAgents bookingAgents);

	BookingAgents update(BookingAgents bookingAgents);

	Boolean exist(BookingAgents bookingAgents);

}

