/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.FlightCosts;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface FlightCostsService {

	FlightCosts getOne(Integer flightNumber);

	List<FlightCosts> findAll();

	Page<FlightCosts> findAll(Pageable pageable);

	Boolean delete(Integer flightNumber);

	FlightCosts create(FlightCosts flightCosts);

	FlightCosts update(FlightCosts flightCosts);

	Boolean exist(FlightCosts flightCosts);

}

