/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.ItineraryLegs;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface ItineraryLegsService {

	ItineraryLegs getOne(Integer reservationId);

	List<ItineraryLegs> findAll();

	Page<ItineraryLegs> findAll(Pageable pageable);

	Boolean delete(Integer reservationId);

	ItineraryLegs create(ItineraryLegs itineraryLegs);

	ItineraryLegs update(ItineraryLegs itineraryLegs);

	Boolean exist(ItineraryLegs itineraryLegs);

}

