/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;



import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.ItineraryReservations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.ItineraryReservationsRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class ItineraryReservationsServiceImpl implements ItineraryReservationsService {

	@Autowired
	private ItineraryReservationsRepository itineraryReservationsRepository;

	@Override
	public ItineraryReservations getOne(Integer reservationId) {
		return itineraryReservationsRepository.findById(reservationId).get();
	}

	@Override
	public Boolean delete(Integer reservationId) {
		if (itineraryReservationsRepository.getOne(reservationId) != null) {
			itineraryReservationsRepository.deleteById(reservationId);
			return true;
		}
		return false;
	}

	@Override
	public ItineraryReservations create(ItineraryReservations itineraryReservations) {
		return itineraryReservationsRepository.save(itineraryReservations);
	}

	@Override
	public ItineraryReservations update(ItineraryReservations itineraryReservationsToUpdate) {
						ItineraryReservations itineraryReservations = itineraryReservationsRepository.getOne(itineraryReservationsToUpdate.getReservationId());
																																		
//				if(itineraryReservationsToUpdate.getAgentId() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getPassengerId() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getReservationStatusCode() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getTicketTypeCode() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getTravelClassCode() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getDataReservationMade() !=null) {
//			
//		}
//				if(itineraryReservationsToUpdate.getNumberInParty() !=null) {
//			
//		}
				return itineraryReservationsRepository.save(itineraryReservations);
	}

	@Override
	public Boolean exist(ItineraryReservations itineraryReservations) {
						return itineraryReservationsRepository.existsById(itineraryReservations.getReservationId());
																																	}

	@Override
	public List<ItineraryReservations> findAll() {
		return itineraryReservationsRepository.findAll();
	}

	@Override
	public Page<ItineraryReservations> findAll(Pageable pageable) {
		return itineraryReservationsRepository.findAll(pageable);
	}
}





