/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;


import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.ItineraryLegs;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.ItineraryLegsRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class ItineraryLegsServiceImpl implements ItineraryLegsService {

	@Autowired
	private ItineraryLegsRepository itineraryLegsRepository;

	@Override
	public ItineraryLegs getOne(Integer reservationId) {
		return itineraryLegsRepository.findById(reservationId).get();
	}

	@Override
	public Boolean delete(Integer reservationId) {
		if (itineraryLegsRepository.getOne(reservationId) != null) {
			itineraryLegsRepository.deleteById(reservationId);
			return true;
		}
		return false;
	}

	@Override
	public ItineraryLegs create(ItineraryLegs itineraryLegs) {
		return itineraryLegsRepository.save(itineraryLegs);
	}

	@Override
	public ItineraryLegs update(ItineraryLegs itineraryLegsToUpdate) {
						ItineraryLegs itineraryLegs = itineraryLegsRepository.getOne(itineraryLegsToUpdate.getReservationId());
										
//				if(itineraryLegsToUpdate.getLegId() !=null) {
//			
//		}
				return itineraryLegsRepository.save(itineraryLegs);
	}

	@Override
	public Boolean exist(ItineraryLegs itineraryLegs) {
						return itineraryLegsRepository.existsById(itineraryLegs.getReservationId());
									}

	@Override
	public List<ItineraryLegs> findAll() {
		return itineraryLegsRepository.findAll();
	}

	@Override
	public Page<ItineraryLegs> findAll(Pageable pageable) {
		return itineraryLegsRepository.findAll(pageable);
	}
}





