/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.ItineraryReservations;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface ItineraryReservationsService {

	ItineraryReservations getOne(Integer reservationId);

	List<ItineraryReservations> findAll();

	Page<ItineraryReservations> findAll(Pageable pageable);

	Boolean delete(Integer reservationId);

	ItineraryReservations create(ItineraryReservations itineraryReservations);

	ItineraryReservations update(ItineraryReservations itineraryReservations);

	Boolean exist(ItineraryReservations itineraryReservations);

}

