/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;


import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.Legs;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.LegsRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class LegsServiceImpl implements LegsService {

	@Autowired
	private LegsRepository legsRepository;

	@Override
	public Legs getOne(Integer legId) {
		return legsRepository.findById(legId).get();
	}

	@Override
	public Boolean delete(Integer legId) {
		if (legsRepository.getOne(legId) != null) {
			legsRepository.deleteById(legId);
			return true;
		}
		return false;
	}

	@Override
	public Legs create(Legs legs) {
		return legsRepository.save(legs);
	}

	@Override
	public Legs update(Legs legsToUpdate) {
						Legs legs = legsRepository.getOne(legsToUpdate.getLegId());
																										
//				if(legsToUpdate.getFlightNumber() !=null) {
//			
//		}
//				if(legsToUpdate.getOriginAirportCode() !=null) {
//			
//		}
//				if(legsToUpdate.getDestinationAirportCode() !=null) {
//			
//		}
				if(legsToUpdate.getActualDepartureTime() !=null) {
			
		}
				if(legsToUpdate.getActualArrivalTime() !=null) {
			
		}
				return legsRepository.save(legs);
	}

	@Override
	public Boolean exist(Legs legs) {
						return legsRepository.existsById(legs.getLegId());
																									}

	@Override
	public List<Legs> findAll() {
		return legsRepository.findAll();
	}

	@Override
	public Page<Legs> findAll(Pageable pageable) {
		return legsRepository.findAll(pageable);
	}
}





