/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;



import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.Passengers;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.PassengersRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class PassengersServiceImpl implements PassengersService {

	@Autowired
	private PassengersRepository passengersRepository;

	@Override
	public Passengers getOne(Integer passengerId) {
		return passengersRepository.findById(passengerId).get();
	}

	@Override
	public Boolean delete(Integer passengerId) {
		if (passengersRepository.getOne(passengerId) != null) {
			passengersRepository.deleteById(passengerId);
			return true;
		}
		return false;
	}

	@Override
	public Passengers create(Passengers passengers) {
		return passengersRepository.save(passengers);
	}

	@Override
	public Passengers update(Passengers passengersToUpdate) {
						Passengers passengers = passengersRepository.getOne(passengersToUpdate.getPassengerId());
																																														
				if(passengersToUpdate.getFirstName() !=null) {
			
		}
				if(passengersToUpdate.getSecondName() !=null) {
			
		}
				if(passengersToUpdate.getLastName() !=null) {
			
		}
//				if(passengersToUpdate.getPhoneNumber() !=null) {
//			
//		}
				if(passengersToUpdate.getEmailAddress() !=null) {
			
		}
				if(passengersToUpdate.getCity() !=null) {
			
		}
				if(passengersToUpdate.getStateProvinceCountry() !=null) {
			
		}
				if(passengersToUpdate.getCountry() !=null) {
			
		}
				if(passengersToUpdate.getOtherPassengerDetails() !=null) {
			
		}
				if(passengersToUpdate.getAddressLines() !=null) {
			
		}
				return passengersRepository.save(passengers);
	}

	@Override
	public Boolean exist(Passengers passengers) {
						return passengersRepository.existsById(passengers.getPassengerId());
																																													}

	@Override
	public List<Passengers> findAll() {
		return passengersRepository.findAll();
	}

	@Override
	public Page<Passengers> findAll(Pageable pageable) {
		return passengersRepository.findAll(pageable);
	}
}





