/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Passengers;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface PassengersService {

	Passengers getOne(Integer passengerId);

	List<Passengers> findAll();

	Page<Passengers> findAll(Pageable pageable);

	Boolean delete(Integer passengerId);

	Passengers create(Passengers passengers);

	Passengers update(Passengers passengers);

	Boolean exist(Passengers passengers);

}

