/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Payments;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface PaymentsService {

	Payments getOne(Integer paymentId);

	List<Payments> findAll();

	Page<Payments> findAll(Pageable pageable);

	Boolean delete(Integer paymentId);

	Payments create(Payments payments);

	Payments update(Payments payments);

	Boolean exist(Payments payments);

}

