/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;


import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.RefCalendar;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.RefCalendarRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class RefCalendarServiceImpl implements RefCalendarService {

	@Autowired
	private RefCalendarRepository refCalendarRepository;

	@Override
	public RefCalendar getOne(Integer dayDate) {
		return refCalendarRepository.findById(dayDate).get();
	}

	@Override
	public Boolean delete(Integer dayDate) {
		if (refCalendarRepository.getOne(dayDate) != null) {
			refCalendarRepository.deleteById(dayDate);
			return true;
		}
		return false;
	}

	@Override
	public RefCalendar create(RefCalendar refCalendar) {
		return refCalendarRepository.save(refCalendar);
	}

	@Override
	public RefCalendar update(RefCalendar refCalendarToUpdate) {
						RefCalendar refCalendar = refCalendarRepository.getOne(refCalendarToUpdate.getDayDate());
														
//				if(refCalendarToUpdate.getDayNumber() !=null) {
//			
//		}
//				if(refCalendarToUpdate.getBusinessDayYn() !=null) {
//			
//		}
				return refCalendarRepository.save(refCalendar);
	}

	@Override
	public Boolean exist(RefCalendar refCalendar) {
						return refCalendarRepository.existsById(refCalendar.getDayDate());
													}

	@Override
	public List<RefCalendar> findAll() {
		return refCalendarRepository.findAll();
	}

	@Override
	public Page<RefCalendar> findAll(Pageable pageable) {
		return refCalendarRepository.findAll(pageable);
	}
}





