/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.RefCalendar;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface RefCalendarService {

	RefCalendar getOne(Integer dayDate);

	List<RefCalendar> findAll();

	Page<RefCalendar> findAll(Pageable pageable);

	Boolean delete(Integer dayDate);

	RefCalendar create(RefCalendar refCalendar);

	RefCalendar update(RefCalendar refCalendar);

	Boolean exist(RefCalendar refCalendar);

}

