/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;


import java.util.List; 

import javax.transaction.Transactional;

import com.example.demo.entity.ReservationPayments;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.repository.ReservationPaymentsRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@Service
@Transactional
public class ReservationPaymentsServiceImpl implements ReservationPaymentsService {

	@Autowired
	private ReservationPaymentsRepository reservationPaymentsRepository;

	@Override
	public ReservationPayments getOne(Integer reservationId) {
		return reservationPaymentsRepository.findById(reservationId).get();
	}

	@Override
	public Boolean delete(Integer reservationId) {
		if (reservationPaymentsRepository.getOne(reservationId) != null) {
			reservationPaymentsRepository.deleteById(reservationId);
			return true;
		}
		return false;
	}

	@Override
	public ReservationPayments create(ReservationPayments reservationPayments) {
		return reservationPaymentsRepository.save(reservationPayments);
	}

	@Override
	public ReservationPayments update(ReservationPayments reservationPaymentsToUpdate) {
						ReservationPayments reservationPayments = reservationPaymentsRepository.getOne(reservationPaymentsToUpdate.getReservationId());
										
//				if(reservationPaymentsToUpdate.getPaymentId() !=null) {
//			
//		}
				return reservationPaymentsRepository.save(reservationPayments);
	}

	@Override
	public Boolean exist(ReservationPayments reservationPayments) {
						return reservationPaymentsRepository.existsById(reservationPayments.getReservationId());
									}

	@Override
	public List<ReservationPayments> findAll() {
		return reservationPaymentsRepository.findAll();
	}

	@Override
	public Page<ReservationPayments> findAll(Pageable pageable) {
		return reservationPaymentsRepository.findAll(pageable);
	}
}





