/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.ReservationPayments;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface ReservationPaymentsService {

	ReservationPayments getOne(Integer reservationId);

	List<ReservationPayments> findAll();

	Page<ReservationPayments> findAll(Pageable pageable);

	Boolean delete(Integer reservationId);

	ReservationPayments create(ReservationPayments reservationPayments);

	ReservationPayments update(ReservationPayments reservationPayments);

	Boolean exist(ReservationPayments reservationPayments);

}

