/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Airports search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AirportsCriteria {

    private String airportName; 
    private String airportLocation; 
    private String otherDetails; 
	// Constructor
	public AirportsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setAirportName(String airportName) {this.airportName = airportName;}
	public String getAirportName() {return this.airportName;}
	public void setAirportLocation(String airportLocation) {this.airportLocation = airportLocation;}
	public String getAirportLocation() {return this.airportLocation;}
	public void setOtherDetails(String otherDetails) {this.otherDetails = otherDetails;}
	public String getOtherDetails() {return this.otherDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(airportName); 
		sb.append("|"); 
		sb.append(airportLocation); 
		sb.append("|"); 
		sb.append(otherDetails); 
        return sb.toString();
	}
}
