/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for BookingAgents search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class BookingAgentsCriteria {

    private String agentName; 
    private String agentDetails; 
	// Constructor
	public BookingAgentsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setAgentName(String agentName) {this.agentName = agentName;}
	public String getAgentName() {return this.agentName;}
	public void setAgentDetails(String agentDetails) {this.agentDetails = agentDetails;}
	public String getAgentDetails() {return this.agentDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(agentName); 
		sb.append("|"); 
		sb.append(agentDetails); 
        return sb.toString();
	}
}
