/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for ItineraryReservations search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ItineraryReservationsCriteria {

    private String dataReservationMade; 
	// Constructor
	public ItineraryReservationsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setDataReservationMade(String dataReservationMade) {this.dataReservationMade = dataReservationMade;}
	public String getDataReservationMade() {return this.dataReservationMade;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(dataReservationMade); 
        return sb.toString();
	}
}
