/*
 * Created on 2018-10-10 ( Date ISO 2018-10-10 - Time 14:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Passengers search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class PassengersCriteria {

    private String firstName; 
    private String secondName; 
    private String lastName; 
    private String emailAddress; 
    private String city; 
    private String stateProvinceCountry; 
    private String country; 
    private String otherPassengerDetails; 
    private String addressLines; 
	// Constructor
	public PassengersCriteria() {
		// Needed empty constructor for serialization
	}

	public void setFirstName(String firstName) {this.firstName = firstName;}
	public String getFirstName() {return this.firstName;}
	public void setSecondName(String secondName) {this.secondName = secondName;}
	public String getSecondName() {return this.secondName;}
	public void setLastName(String lastName) {this.lastName = lastName;}
	public String getLastName() {return this.lastName;}
	public void setEmailAddress(String emailAddress) {this.emailAddress = emailAddress;}
	public String getEmailAddress() {return this.emailAddress;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setStateProvinceCountry(String stateProvinceCountry) {this.stateProvinceCountry = stateProvinceCountry;}
	public String getStateProvinceCountry() {return this.stateProvinceCountry;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOtherPassengerDetails(String otherPassengerDetails) {this.otherPassengerDetails = otherPassengerDetails;}
	public String getOtherPassengerDetails() {return this.otherPassengerDetails;}
	public void setAddressLines(String addressLines) {this.addressLines = addressLines;}
	public String getAddressLines() {return this.addressLines;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(firstName); 
		sb.append("|"); 
		sb.append(secondName); 
		sb.append("|"); 
		sb.append(lastName); 
		sb.append("|"); 
		sb.append(emailAddress); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(stateProvinceCountry); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherPassengerDetails); 
		sb.append("|"); 
		sb.append(addressLines); 
        return sb.toString();
	}
}
