package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Airports generated by hbm2java
 */
@Entity
@Table(name = "airports")
public class Airports implements java.io.Serializable {

	private Integer airportCode;
	private String airportName;
	private String airportLocation;
	private String otherDetails;

	public Airports() {
	}

	public Airports(String airportName, String airportLocation, String otherDetails) {
		this.airportName = airportName;
		this.airportLocation = airportLocation;
		this.otherDetails = otherDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "airport_code", unique = true, nullable = false)
	public Integer getAirportCode() {
		return this.airportCode;
	}

	public void setAirportCode(Integer airportCode) {
		this.airportCode = airportCode;
	}

	@Column(name = "airport_name", nullable = false, length = 250)
	public String getAirportName() {
		return this.airportName;
	}

	public void setAirportName(String airportName) {
		this.airportName = airportName;
	}

	@Column(name = "airport_location", nullable = false, length = 250)
	public String getAirportLocation() {
		return this.airportLocation;
	}

	public void setAirportLocation(String airportLocation) {
		this.airportLocation = airportLocation;
	}

	@Column(name = "other_details", nullable = false, length = 250)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
