package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookingAgents generated by hbm2java
 */
@Entity
@Table(name = "booking_agents")
public class BookingAgents implements java.io.Serializable {

	private Integer agentId;
	private String agentName;
	private String agentDetails;

	public BookingAgents() {
	}

	public BookingAgents(String agentName, String agentDetails) {
		this.agentName = agentName;
		this.agentDetails = agentDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "agent_id", unique = true, nullable = false)
	public Integer getAgentId() {
		return this.agentId;
	}

	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	@Column(name = "agent_name", nullable = false, length = 250)
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	@Column(name = "agent_details", nullable = false, length = 250)
	public String getAgentDetails() {
		return this.agentDetails;
	}

	public void setAgentDetails(String agentDetails) {
		this.agentDetails = agentDetails;
	}

}
