package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlightSchedules generated by hbm2java
 */
@Entity
@Table(name = "flight_schedules")
public class FlightSchedules implements java.io.Serializable {

	private Integer flightNumber;
	private int airlineCode;
	private int usualAircraftTypeCode;
	private int originAirportCode;
	private int destinationAirportCode;
	private Date departureTime;
	private Date arrvialTime;

	public FlightSchedules() {
	}

	public FlightSchedules(int airlineCode, int usualAircraftTypeCode, int originAirportCode,
			int destinationAirportCode, Date departureTime, Date arrvialTime) {
		this.airlineCode = airlineCode;
		this.usualAircraftTypeCode = usualAircraftTypeCode;
		this.originAirportCode = originAirportCode;
		this.destinationAirportCode = destinationAirportCode;
		this.departureTime = departureTime;
		this.arrvialTime = arrvialTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "flight_number", unique = true, nullable = false)
	public Integer getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(Integer flightNumber) {
		this.flightNumber = flightNumber;
	}

	@Column(name = "airline_code", nullable = false)
	public int getAirlineCode() {
		return this.airlineCode;
	}

	public void setAirlineCode(int airlineCode) {
		this.airlineCode = airlineCode;
	}

	@Column(name = "usual_aircraft_type_code", nullable = false)
	public int getUsualAircraftTypeCode() {
		return this.usualAircraftTypeCode;
	}

	public void setUsualAircraftTypeCode(int usualAircraftTypeCode) {
		this.usualAircraftTypeCode = usualAircraftTypeCode;
	}

	@Column(name = "origin_airport_code", nullable = false)
	public int getOriginAirportCode() {
		return this.originAirportCode;
	}

	public void setOriginAirportCode(int originAirportCode) {
		this.originAirportCode = originAirportCode;
	}

	@Column(name = "destination_airport_code", nullable = false)
	public int getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(int destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "departure_time", nullable = false, length = 10)
	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "arrvial_time", nullable = false, length = 10)
	public Date getArrvialTime() {
		return this.arrvialTime;
	}

	public void setArrvialTime(Date arrvialTime) {
		this.arrvialTime = arrvialTime;
	}

}
