package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItineraryReservations generated by hbm2java
 */
@Entity
@Table(name = "itinerary_reservations")
public class ItineraryReservations implements java.io.Serializable {

	private Integer reservationId;
	private int agentId;
	private int passengerId;
	private int reservationStatusCode;
	private int ticketTypeCode;
	private int travelClassCode;
	private String dataReservationMade;
	private int numberInParty;

	public ItineraryReservations() {
	}

	public ItineraryReservations(int agentId, int passengerId, int reservationStatusCode, int ticketTypeCode,
			int travelClassCode, String dataReservationMade, int numberInParty) {
		this.agentId = agentId;
		this.passengerId = passengerId;
		this.reservationStatusCode = reservationStatusCode;
		this.ticketTypeCode = ticketTypeCode;
		this.travelClassCode = travelClassCode;
		this.dataReservationMade = dataReservationMade;
		this.numberInParty = numberInParty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reservation_id", unique = true, nullable = false)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@Column(name = "agent_id", nullable = false)
	public int getAgentId() {
		return this.agentId;
	}

	public void setAgentId(int agentId) {
		this.agentId = agentId;
	}

	@Column(name = "passenger_id", nullable = false)
	public int getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(int passengerId) {
		this.passengerId = passengerId;
	}

	@Column(name = "reservation_status_code", nullable = false)
	public int getReservationStatusCode() {
		return this.reservationStatusCode;
	}

	public void setReservationStatusCode(int reservationStatusCode) {
		this.reservationStatusCode = reservationStatusCode;
	}

	@Column(name = "ticket_type_code", nullable = false)
	public int getTicketTypeCode() {
		return this.ticketTypeCode;
	}

	public void setTicketTypeCode(int ticketTypeCode) {
		this.ticketTypeCode = ticketTypeCode;
	}

	@Column(name = "travel_class_code", nullable = false)
	public int getTravelClassCode() {
		return this.travelClassCode;
	}

	public void setTravelClassCode(int travelClassCode) {
		this.travelClassCode = travelClassCode;
	}

	@Column(name = "data_reservation_made", nullable = false, length = 250)
	public String getDataReservationMade() {
		return this.dataReservationMade;
	}

	public void setDataReservationMade(String dataReservationMade) {
		this.dataReservationMade = dataReservationMade;
	}

	@Column(name = "number_in_party", nullable = false)
	public int getNumberInParty() {
		return this.numberInParty;
	}

	public void setNumberInParty(int numberInParty) {
		this.numberInParty = numberInParty;
	}

}
