package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItineraryLegs generated by hbm2java
 */
@Entity
@Table(name = "itinerary_legs")
public class ItineraryLegs implements java.io.Serializable {

	private Integer reservationId;
	private int legId;

	public ItineraryLegs() {
	}

	public ItineraryLegs(int legId) {
		this.legId = legId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reservation_id", unique = true, nullable = false)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@Column(name = "leg_id", nullable = false)
	public int getLegId() {
		return this.legId;
	}

	public void setLegId(int legId) {
		this.legId = legId;
	}

}
