package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Legs generated by hbm2java
 */
@Entity
@Table(name = "legs")
public class Legs implements java.io.Serializable {

	private Integer legId;
	private int flightNumber;
	private int originAirportCode;
	private int destinationAirportCode;
	private Date actualDepartureTime;
	private Date actualArrivalTime;

	public Legs() {
	}

	public Legs(int flightNumber, int originAirportCode, int destinationAirportCode, Date actualDepartureTime,
			Date actualArrivalTime) {
		this.flightNumber = flightNumber;
		this.originAirportCode = originAirportCode;
		this.destinationAirportCode = destinationAirportCode;
		this.actualDepartureTime = actualDepartureTime;
		this.actualArrivalTime = actualArrivalTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "leg_id", unique = true, nullable = false)
	public Integer getLegId() {
		return this.legId;
	}

	public void setLegId(Integer legId) {
		this.legId = legId;
	}

	@Column(name = "flight_number", nullable = false)
	public int getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(int flightNumber) {
		this.flightNumber = flightNumber;
	}

	@Column(name = "origin_airport_code", nullable = false)
	public int getOriginAirportCode() {
		return this.originAirportCode;
	}

	public void setOriginAirportCode(int originAirportCode) {
		this.originAirportCode = originAirportCode;
	}

	@Column(name = "destination_airport_code", nullable = false)
	public int getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(int destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "actual_departure_time", nullable = false, length = 10)
	public Date getActualDepartureTime() {
		return this.actualDepartureTime;
	}

	public void setActualDepartureTime(Date actualDepartureTime) {
		this.actualDepartureTime = actualDepartureTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "actual_arrival_time", nullable = false, length = 10)
	public Date getActualArrivalTime() {
		return this.actualArrivalTime;
	}

	public void setActualArrivalTime(Date actualArrivalTime) {
		this.actualArrivalTime = actualArrivalTime;
	}

}
