package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Passengers generated by hbm2java
 */
@Entity
@Table(name = "passengers")
public class Passengers implements java.io.Serializable {

	private Integer passengerId;
	private String firstName;
	private String secondName;
	private String lastName;
	private int phoneNumber;
	private String emailAddress;
	private String city;
	private String stateProvinceCountry;
	private String country;
	private String otherPassengerDetails;
	private String addressLines;

	public Passengers() {
	}

	public Passengers(String firstName, String secondName, String lastName, int phoneNumber, String emailAddress,
			String city, String stateProvinceCountry, String country, String otherPassengerDetails,
			String addressLines) {
		this.firstName = firstName;
		this.secondName = secondName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.city = city;
		this.stateProvinceCountry = stateProvinceCountry;
		this.country = country;
		this.otherPassengerDetails = otherPassengerDetails;
		this.addressLines = addressLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passenger_id", unique = true, nullable = false)
	public Integer getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(Integer passengerId) {
		this.passengerId = passengerId;
	}

	@Column(name = "first_name", nullable = false, length = 250)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "second_name", nullable = false, length = 250)
	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	@Column(name = "last_name", nullable = false, length = 250)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phone_number", nullable = false)
	public int getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(int phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email_address", nullable = false, length = 250)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "city", nullable = false, length = 250)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state_province_country", nullable = false, length = 250)
	public String getStateProvinceCountry() {
		return this.stateProvinceCountry;
	}

	public void setStateProvinceCountry(String stateProvinceCountry) {
		this.stateProvinceCountry = stateProvinceCountry;
	}

	@Column(name = "country", nullable = false, length = 250)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "other_passenger_details", nullable = false, length = 250)
	public String getOtherPassengerDetails() {
		return this.otherPassengerDetails;
	}

	public void setOtherPassengerDetails(String otherPassengerDetails) {
		this.otherPassengerDetails = otherPassengerDetails;
	}

	@Column(name = "address_lines", nullable = false, length = 250)
	public String getAddressLines() {
		return this.addressLines;
	}

	public void setAddressLines(String addressLines) {
		this.addressLines = addressLines;
	}

}
