package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefCalendar generated by hbm2java
 */
@Entity
@Table(name = "ref_calendar")
public class RefCalendar implements java.io.Serializable {

	private Integer dayDate;
	private int dayNumber;
	private int businessDayYn;

	public RefCalendar() {
	}

	public RefCalendar(int dayNumber, int businessDayYn) {
		this.dayNumber = dayNumber;
		this.businessDayYn = businessDayYn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "day_date", unique = true, nullable = false)
	public Integer getDayDate() {
		return this.dayDate;
	}

	public void setDayDate(Integer dayDate) {
		this.dayDate = dayDate;
	}

	@Column(name = "day_number", nullable = false)
	public int getDayNumber() {
		return this.dayNumber;
	}

	public void setDayNumber(int dayNumber) {
		this.dayNumber = dayNumber;
	}

	@Column(name = "business_day_yn", nullable = false)
	public int getBusinessDayYn() {
		return this.businessDayYn;
	}

	public void setBusinessDayYn(int businessDayYn) {
		this.businessDayYn = businessDayYn;
	}

}
