package com.example.demo.entity;
// Generated Oct 10, 2018 2:06:31 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReservationPayments generated by hbm2java
 */
@Entity
@Table(name = "reservation_payments")
public class ReservationPayments implements java.io.Serializable {

	private Integer reservationId;
	private int paymentId;

	public ReservationPayments() {
	}

	public ReservationPayments(int paymentId) {
		this.paymentId = paymentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reservation_id", unique = true, nullable = false)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@Column(name = "payment_id", nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

}
